# Generated by Django 5.0.7 on 2025-08-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_attempt_attemptquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='attemptquestion',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='APILog',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='AttemptQuestion',
        ),
    ]
